[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
apechain = "https://jenkins.rpc.caldera.xyz/http"
arbitrum = "https://public.stackup.sh/api/v1/node/arbitrum-sepolia"
aurora = "https://testnet.aurora.dev"
avail = "https://op-plasma-avail-testnet.alt.technology"
base = "https://base-sepolia-rpc.publicnode.com"
celo = "https://alfajores-forno.celo-testnet.org"
morph = "https://rpc-holesky.morphl2.io"
rootstock = "https://mycrypto.testnet.rsk.co"
scroll = "https://sepolia-rpc.scroll.io"
zircuit = "https://zircuit1.p2pify.com"

[etherscan]
arbitrum = { key = "CAH9QG46T9H4WZ6U47MPKHWRRYCXDAN6BG" }