[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
apechain = "${APECHAIN_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
celo = "${CELO_RPC_URL}"
morph = "${MORPH_RPC_URL}"
rootstock = "${ROOTSTOCK_RPC_URL}"
scroll = "${SCROLL_RPC_URL}"
zircuit = "${ZIRCUIT_RPC_URL}"